services:
  keycloak:
    build: keycloak
    command:
      - start-dev
      - --spi-login-freemarker-enabled=false
      - --spi-login-custom-freemarker-enabled=true
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      KC_METRICS_ENABLED: 'true'
      KC_HOSTNAME_STRICT: 'false'
      # API da Receita
      RC_RFB_API_TOKEN: $KEYCLOAK_RC_RFB_API_TOKEN
    ports:
      - "8080:8080"

  keycloak-config-cli:
    image: adorsys/keycloak-config-cli:6.4.0-26.1.0
    env_file: .env
    depends_on:
      - keycloak
    environment:
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: $KEYCLOAK_ADMIN_PASSWORD
      KEYCLOAK_AVAILABILITYCHECK_ENABLED: 'true'
      IMPORT_VARSUBSTITUTION_ENABLED: 'true'
      MAIL_SMTP_HOST: smtp4dev
      MAIL_SMTP_FROM: noreply@keycloak.playground
      MAIL_SMTP_PORT: 25
      # API de Biometria
      FACIAL_BIOMETRICS_API_URL: https://api.hml.confia.net.br
      FACIAL_BIOMETRICS_API_KEY: $KEYCLOAK_FACIAL_BIOMETRICS_API_KEY
      # Autenticação via SMS
      SMS_AUTHENTICATION_ACCESS_KEY: AKIA2Y4IEWJKMJNNQ2HM
      SMS_AUTHENTICATION_SECRET_KEY: $KEYCLOAK_SMS_AUTHENTICATION_SECRET_KEY
    volumes:
      - ./keycloak-config-cli/:/config

  smtp4dev:
    image: rnwood/smtp4dev:v3.6
    environment:
      ServerOptions__Port: 25
    ports:
      - 8000:80
  
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: entropydb
      MYSQL_USER: entropyuser
      MYSQL_PASSWORD: entropypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  entropy-api:
    build:
      context: ./node
    ports:
      - "3000:3000"
    depends_on:
      - mysql

volumes:
  mysql_data:

